// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFD3z0zF8SjAgY9YIFS59-2cQphqowPew',
    appId: '1:163088815905:android:7b7ada390471c0024f9060',
    messagingSenderId: '163088815905',
    projectId: 'target-control-0-ef81c',
    databaseURL: 'https://target-control-0-ef81c-default-rtdb.firebaseio.com',
    storageBucket: 'target-control-0-ef81c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlErdda1Qzi2vVo956paj79gOLflLDM1M',
    appId: '1:163088815905:ios:304a3f75def428fe4f9060',
    messagingSenderId: '163088815905',
    projectId: 'target-control-0-ef81c',
    databaseURL: 'https://target-control-0-ef81c-default-rtdb.firebaseio.com',
    storageBucket: 'target-control-0-ef81c.appspot.com',
    iosClientId: '163088815905-l2qts687i2s8lidjfmnftfjgm29qd81n.apps.googleusercontent.com',
    iosBundleId: 'com.example.countpeople',
  );
}
